### ISSUE TITLE
`ign` command version comparison needs natural sort order

### ISSUE THREAD

**Issue by peci1** [ignitionrobotics/ign-tools#48]
## Environment
* OS Version: Ubuntu 18.04
* Source or binary build? Binary 1.1.0

## Description
* Expected behavior: `ign sdf` launches the latest installed sdformat command
* Actual behavior: It launches an older one.

## Steps to reproduce
1. install `libsdformat8-dev`
2. install `libsdformat10-dev`
3. take a SDF 1.7 model and pass it to `ign sdf --check`.
4. The check fails saying that SDF 1.7 is too new for this tool to work with. That points at sdformat 8 being used.

I bet the problem lies in

https://github.com/ignitionrobotics/ign-tools/blob/d32853a9b4ebf21c3421f7e903e51a9c45e15849/src/ign.in#L145

which looks like C-order rather than natural order. But as my Ruby knowledge is limited, I don't know how to fix it correctly.

My system reports these version of sdformat:

    8.9.1
    10.3.0

**Comment by scpeters** [comment]
we can copy some of the ruby code from homebrew's [version.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/version.rb) file to handle version parsing and sorting

or we could try to add swig bindings for the `ignition::math::SemanticVersion` class

**Comment by chapulina** [comment]
> add swig bindings for the ignition::math::SemanticVersion class

That's part of https://github.com/ignitionrobotics/ign-math/issues/101

Note that it would add a dependency to `ign-math`, and this may cause a circular dependency if we ever decide to add `ign-tools` to `ign-math` as part of https://github.com/ignitionrobotics/ign-math/issues/198.

**Comment by caguero** [comment]
See pull request #50 .
