### ISSUE TITLE
Too strict looking for config paths, difficult to combine different installs

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-tools#8]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-tools/issues/8)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
# Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Q&A board for common solutions: http://answers.gazebosim.org
    * Checked that your issue isn't already filed.
    * Checked that there is not already an Ignition package that provides the described functionality: https://ignitionrobotics.org/libs

# Description 

By default, `ign-tools` will look at its own installed path for yaml config files of other libraries. This works fine when all libraries have been installed from debs, because they all end up under the same directory structure under `/usr`. But it fails for example when one was installed from debs and the other was installed from source to `/usr/local` or some other custom path.

# Steps to Reproduce

1. Install `ign-tools` from debs: `sudo apt install libignition-tools-dev`
1. Build another library from source, such as `ign-msgs`.
1. Try to run `ign msg`, and `ign-tools` won't be able to find the `msg` command.

**Expected behavior:**  

Ignition tools should find the library, either by default, or with some documented configuration steps.

**Actual behavior:**

The command can't be found.

# Additional Information

This discussion started on issue #2, look there for more context.

A partial solution is to set the `IGN_CONFIG_PATH` variable at runtime pointing at the library to be found. This works well if you only need to find libraries in a single path, but doesn't work for several libraries installed to different paths, because `IGN_CONFIG_PATH` only accepts a single path.

Another workaround is to use symlinks as described [here](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-tools/issues/2/create-debian-package#comment-51546533), for example:

~~~
mkdir ~/.ignition/tools/configs -p
cd ~/.ignition/tools/configs/
ln -s ~/ws/install/ignition-transport6/share/ignition/transport6.yaml .
ln -s ~/ws/install/ignition-gui1/share/ignition/gui1.yaml .
...
export IGN_CONFIG_PATH=$HOME/.ignition/tools/configs
~~~

**Comment by scpeters** [comment]
multiple paths can now be specified in `IGN_CONFIG_PATH` using the `:` delimiter as of [BitBucket pull request 13](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-tools/pull-requests/13)

**Comment by chapulina** [comment]
Ohh I think we can remove a bunch of troubleshooting sections then, like this one:

https://github.com/ignitionrobotics/ign-fuel-tools/#known-issue-of-command-line-tools
